#!/bin/sh
xinput set-prop "HUION Huion Tablet Pen stylus" "Coordinate Transformation Matrix" 0.5, 0, 0.5, 0, 1, 0, 0, 0, 1
xsetwacom --set "HUION Huion Tablet Pad pad" Button 3 "key +Print"
xsetwacom --set "HUION Huion Tablet Pad pad" Button 2 "key control alt shift +F12"
xsetwacom --set "HUION Huion Tablet Pad pad" Button 1 "key control alt shift +F11"
xsetwacom --set "HUION Huion Tablet Pen stylus" Button 3 "key control +Z"