PREFIX ?= /usr

all:
	        @echo RUN \'make install\' to install umutfetch

install:
	        @install -Dm755 umutfetch $(DESTDIR)$(PREFIX)/bin/umutfetch

uninstall:
	        @rm -f $(DESTDIR)$(PREFIX)/bin/umutfetch
